import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_ktx: String = "androidx.activity:activity-ktx:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val datastore_preferences: String = "androidx.datastore:datastore-preferences:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:_"

    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val paging_runtime: String = "androidx.paging:paging-runtime:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx:_"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val startup_runtime: String = "androidx.startup:startup-runtime:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    public const val com_github_bumptech_glide_compiler: String =
            "com.github.bumptech.glide:compiler:_"

    public const val glide: String = "com.github.bumptech.glide:glide:_"

    public const val persistentcookiejar: String = "com.github.franmontiel:PersistentCookieJar:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val dagger: String = "com.google.dagger:dagger:_"

    public const val dagger_android: String = "com.google.dagger:dagger-android:_"

    public const val dagger_android_processor: String =
            "com.google.dagger:dagger-android-processor:_"

    public const val dagger_android_support: String = "com.google.dagger:dagger-android-support:_"

    public const val dagger_compiler: String = "com.google.dagger:dagger-compiler:_"

    public const val retrofit2_rxjava2_adapter: String =
            "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:_"

    public const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:_"

    public const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:_"

    public const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val sdk: String = "com.tencent.tbs.tbssdk:sdk:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"
}
